name: Price Check Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MONGO_DB_CONNECTION_URL: ${{ secrets.MONGO_DB_CONNECTION_URL }}
  MONGODB_ATLAS_PROJECT_ID: ${{ secrets.MONGODB_ATLAS_PROJECT_ID }}
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
  
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt 

    - name: Get the public IP of this runner
      id: get_gh_runner_ip
      run: echo "ip_address=$(curl https://checkip.amazonaws.com)" >> $GITHUB_ENV

    - name: Setup MongoDB Atlas CLI
      uses: mongodb/atlas-github-action@v0.2.0

    - name: Configure MongoDB Atlas CLI
      run: |
        mkdir -p ~/.config/mongocli
        cat <<EOF > ~/.config/mongocli/config.toml
        [default]
        org_id = ${MONGODB_ATLAS_ORG_ID}
        output = 'json'
        private_api_key = ${MONGODB_ATLAS_PRIVATE_KEY}
        project_id = ${MONGODB_ATLAS_PROJECT_ID}
        public_api_key = ${MONGODB_ATLAS_PUBLIC_KEY}
        service = 'cloud'
        EOF

    - name: Add runner IP to MongoDB access list
      run: |
        atlas accessLists create ${{ env.ip_address }} --type ipAddress --profile="default" --comment "Temporary access for GH Action"

    - name: Run Python script with secret
      run: |
        python macys_price_check.py

    - name: Remove GH runner IP from MongoDB access list
      if: always()
      run: |
        atlas accessLists delete ${{ env.ip_address }} --projectId ${{ env.MONGODB_ATLAS_PROJECT_ID }} --force